services:
  postgres:
    image: postgres:16.3
    container_name: personal-vault-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-personal_vault_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - personal_vault_postgres_data:/var/lib/postgresql/data

volumes:
  # Give the volume a unique name so it doesn't overwrite your other project's data
  personal_vault_postgres_data: